server:
  port: 8080
springdoc:
  swagger-ui:
    path: /docs.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    query-config-enabled: true
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      config:
        server-addr: 192.168.10.21:48848
        file-extension: yaml
      discovery:
        server-addr: 192.168.10.21:48848
