
retrofit:
  # 全局转换器工厂(已经内置了组件扩展的转换器工厂，这里请勿重复配置)
  global-converter-factories:
    - retrofit2.converter.jackson.JacksonConverterFactory
  # 全局调用适配器工厂(已经内置了组件扩展的调用适配器工厂，这里请勿重复配置)
#  global-call-adapter-factories:
  # 全局日志打印配置
  global-log:
    # 启用全局日志打印
    enable: true
    # 全局日志打印级别
    log-level: info
    # 全局日志打印策略
    log-strategy: body
  # 全局重试配置
  global-retry:
    # 是否启用全局重试
    enable: true
    # 全局重试间隔时间
    interval-ms: 1000
    # 全局最大重试次数
    max-retries: 3
    # 全局重试规则
    retry-rules:
      - response_status_not_2xx
      - occur_io_exception

  # 熔断降级配置
#  degrade:
#    # 熔断降级类型。默认none，表示不启用熔断降级
#    degrade-type: sentinel
#    global-sentinel-degrade:
#      # 是否开启
#      enable: true
#      # 各降级策略对应的阈值。平均响应时间(ms)，异常比例(0-1)，异常数量(1-N)
#      count: 3000
#      # 熔断时长，单位为 s
#      time-window: 5
#      # 降级策略（0：平均响应时间；1：异常比例；2：异常数量）
#      grade: 0

taobao:
  baseUrl: https://api.m.taobao.com/rest/
  accessKeyId: accessKeyIdsdfsdfdsf
  accessKeySecret: accessKeySecretsadfsadfsdfsdf
tuna:
  baseUrl: https://img1.baidu.com/it/
  fileKey:



#taobao time api
#http://api.m.taobao.com/rest/api3.do?api=mtop.common.getTimestamp

#
# https://img1.baidu.com/it/u=4276151928,2257626089&fm=253&fmt=auto&app=138&f=JPEG?w=500&h=313
