#
#retrofit:
#  # 全局转换器工厂(已经内置了组件扩展的转换器工厂，这里请勿重复配置)
#  global-converter-factories:
#    - retrofit2.converter.jackson.JacksonConverterFactory
#  # 全局调用适配器工厂(已经内置了组件扩展的调用适配器工厂，这里请勿重复配置)
#  global-call-adapter-factories:
#  # 全局日志打印配置
#  global-log:
#    # 启用全局日志打印
#    enable: true
#    # 全局日志打印级别
#    log-level: info
#    # 全局日志打印策略
#    log-strategy: body
#
#
#  # 全局重试配置
#  global-retry:
#    # 是否启用全局重试
#    enable: true
#    # 全局重试间隔时间
#    interval-ms: 1000
#    # 全局最大重试次数
#    max-retries: 3
#    # 全局重试规则
#    retry-rules:
#      - response_status_not_2xx
#      - occur_io_exception
#
#  # 熔断降级配置
#  degrade:
#    # 熔断降级类型。默认none，表示不启用熔断降级
#    degrade-type: sentinel
#    global-sentinel-degrade:
#      # 是否开启
#      enable: true
#      # 各降级策略对应的阈值。平均响应时间(ms)，异常比例(0-1)，异常数量(1-N)
#      count: 1000
#
##test:
##  baseUrl: http://localhost:9000/openservice/
##  accessKeyId: sdfsdfdsf
##  accessKeySecret: sadfsadfsdfsdf