spring:
  #  mvc:
  #    pathmatch:
  #      matching-strategy: ant_path_matcher
  datasource:
    # ?????Druid???
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xinyi.blazings.win:53306/sqlintroduction?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: UmingambEnerARLEYBoRtHOT
    druid:
      # ????????
      # ???????????
      initial-size: 5
      min-idle: 2
      maxActive: 15
      # ?????????????
      maxWait: 60000
      # ???????????????????????????????
      timeBetweenEvictionRunsMillis: 60000
      # ??????????????????????
      minEvictableIdleTimeMillis: 600000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # ??PSCache??????????PSCache???
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # ?????????filters????????sql?????'wall'?????
      filters: stat,wall,slf4j
      # ??connectProperties?????mergeSql????SQL??
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000