server:
  port: 8081
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: xinyi.blazings.win:58848
      config:
        server-addr: xinyi.blazings.win:58848
        file-extension: nacos-config.yaml
