server:
  port: 8081
springdoc:
  swagger-ui:
    path: /docs.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    query-config-enabled: true
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      config:
        server-addr: 192.168.10.21:58848
        file-extension: yaml
      discovery:
        server-addr: 192.168.10.21:58848
