spring:
  messages:
    encoding: UTF-8
  application:
    name: suanfa_mvcapp
server:
  port: 50080
  tomcat:
    uri-encoding: UTF-8

springdoc:
  swagger-ui:
    path: /docs.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    query-config-enabled: true
#打开所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: ALWAYS
  metrics:
    export:
      prometheus:
        enabled: true

