springdoc:
  swagger-ui:
    path: /docs.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    query-config-enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
# Sa-Token-Quick-Login 配置
sa:
  # 登录账号
  name: sa
  # 登录密码
  pwd: 123456
  # 是否自动随机生成账号密码 (此项为true时, name与pwd失效)
  auto: false
  # 是否开启全局认证(关闭后将不再强行拦截)
  auth: false
  # 登录页标题
  title: 登录
  # 是否显示底部版权信息
  copr: false
  # 指定拦截路径
  include: '/actuator'
  # 指定排除路径
  # exclude: /sss,/fff
